networks:
    authentik:
        external: false
    redis:
        external: true

services:
  ts-server:
    image: tailscale/tailscale:latest
    hostname: authentik
    environment:
      - TS_AUTHKEY=$TS_AUTH_KEY
      - TS_EXTRA_ARGS=--advertise-tags=tag:authentik
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - ${DATA_LOCATION}/tailscale:/var/lib/tailscale
      - ./tailscale:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      - authentik

  postgresql:
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ${DATA_LOCATION}/db:/var/lib/postgresql/18/docker
    networks:
      - authentik

#   redis:
#     command: --save 60 1 --loglevel warning
#     healthcheck:
#       interval: 30s
#       retries: 5
#       start_period: 20s
#       test:
#       - CMD-SHELL
#       - redis-cli ping | grep PONG
#       timeout: 3s
#     image: docker.io/library/redis:alpine
#     restart: unless-stopped
#     volumes:
#     - redis:/data

  authentik-server:
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    #   redis:
    #     condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.4}
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    volumes:
    - ${DATA_LOCATION}/media:/media
    - ${DATA_LOCATION}/custom-templates:/templates
    networks:
      - authentik
      - redis

  worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    #   redis:
    #     condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.4}
    restart: unless-stopped
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DATA_LOCATION}/media:/media
    - ${DATA_LOCATION}/certs:/certs
    - ${DATA_LOCATION}/custom-templates:/templates
    networks:
      - authentik
      - redis

volumes:
  database:
    driver: local
  redis:
    driver: local
